### ISSUE TITLE
Any thoughts on adding short descriptions and categories/subcategories?

### ISSUE THREAD

**Issue by TryTryAgain** [warior456/Kerbal-Space-Program-2-modlist#11]
Thanks for putting this together, I'm sure there will be many more in a short time. Any thoughts on adding short descriptions and categories/subcategories?

**Comment by warior456** [comment]
We're currently looking into switching to github pages and json format to make this possible

**Comment by TryTryAgain** [comment]
Looking forward to it, thanks!
