### ISSUE TITLE
the current test jsons do not show

### ISSUE THREAD

**Issue by warior456** [warior456/Kerbal-Space-Program-2-modlist#12]
![image](https://user-images.githubusercontent.com/66562258/222480419-2aaee4af-3c13-4a07-93d5-22260f4e13e1.png)

[warior456.github.io-1677772520162.log](https://github.com/warior456/KSP-2-tools-and-mods/files/10873135/warior456.github.io-1677772520162.log)

**Comment by warior456** [comment]
@amahlaka do you know how to fix this?

**Comment by warior456** [comment]
fixed by removing [0] brackets from FileData

**Comment by Kiteflow** [comment]
Please can we not migrate to those JSON files. They're stupid, clunky and are just going to make adding mods 10x harder. It's just completely reinventing stuff like CKAN, which you've already been questioned about. This was useful in the beginning as there was not a particularly good central repository of all the mods (very few posted to the forums and some not even on SpaceDock).

If you want to do a website, do something easy to edit with: title, author, description, link (like literally each mod should be like a markdown file or something really simple and easy). This is incredibly temporary and just kind of pointless in my opinion.

Solutions I propose:
- Migrating everything to the forums (would need to get mod authors to do that but it is probably good for now)
- Redoing the README.md to include simple descriptions and mod categories (I am happy to do this) with the hope that it's just enough time to tie over until CKAN supports KSP 2
- Doing a similar thing to the JSON files, but using a JS framework (something like Astro would be good) and simple markdown file mods. Hopefully quick and easy enough to again tie us over until CKAN supports KSP2

I am in favour of any of them, but definitely not on the current way this seems to be going.

**Comment by warior456** [comment]
Either your last point or the one before that is fine for me, we can try encouraging mod authors to post their stuff on spacedock and the ksp2 forums but not all of them will do it
