### ISSUE TITLE
Please don't re-invent the CKAN wheel

### ISSUE THREAD

**Issue by HebaruSan** [warior456/Kerbal-Space-Program-2-modlist#3]
CKAN is a mod manager for KSP1, which supports a fully featured metadata format that handles dependencies/conflicts, compatibility, complex installation instructions, regularly checking for updates, and more:

- <https://forum.kerbalspaceprogram.com/index.php?/topic/197082-ckan-the-comprehensive-kerbal-archive-network-v1312-juno/>
- <https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md>
- <https://github.com/KSP-CKAN/NetKAN-Infra>

We have started planning how to support KSP2, but couldn't act on it until the game was released (and we may still hold off until the core game can load mods without a third-party mod loader):

- KSP-CKAN/CKAN#2863

There are some simple JSON-format files in this repo with mod descriptions and download locations, which is where CKAN started about 8-ish years ago. Don't re-invent the wheel. Consider using what already works.

**Comment by warior456** [comment]
we won't the json files are just leftovers

**Comment by HebaruSan** [comment]
That's good to hear. 🎉 
If you have any questions or want to collaborate on anything related to KSP2 mods, please don't hesitate to reach out.


https://discord.gg/Mb4nXQD
